service:
  name: dale
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    # This CLI parameter should only contain one of two values "LOCAL" or "AWS".
    # If no value is provided "LOCAL" will be used
    DB_CONFIG: ${opt:dbConfig}

functions:
  store-incoming-event:
    handler: api/incoming-event.store
    role: arn:aws:iam::292052096336:role/dale-lambda-all-mighty
    events:
      - http:
          method: post
          path: /incoming-event
  get-incoming-events:
    handler: api/incoming-event.get
    role: arn:aws:iam::292052096336:role/dale-lambda-all-mighty
    events:
      - http:
          method: get
          path: /incoming-event
