service:
  name: dale
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  profile: personal

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: /hello
